name: Security Scan

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  scan-images:
    name: Scan Frontend & Backend Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      issues: write
    strategy:
      matrix:
        project: [frontend, backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image for scanning
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.project }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/turnier-manager-${{ matrix.project }}:scan-latest
      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/turnier-manager-${{ matrix.project }}:scan-latest'
          format: 'template'
          template: '@/contrib/issue.tpl'
          output: 'trivy-results.md'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Create GitHub Issue on failure
        if: failure() && steps.trivy-scan.outcome == 'failure'
        uses: actions/create-issue@v2
        with:
          title: '🛡️ Sicherheits-Scan fehlgeschlagen für ${{ matrix.project }}'
          body: |
            Der automatische Trivy-Scan hat eine oder mehrere kritische/hohe Schwachstellen im Docker-Image für **${{ matrix.project }}** gefunden.
            Bitte überprüfen Sie die Details unten und aktualisieren Sie die betroffenen Abhängigkeiten.
            ### Scan-Ergebnisse
            ${{ steps.trivy-scan.outputs.result }}
          labels: security, vulnerability