name: Security Scan

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  scan-images:
    name: Scan Frontend & Backend Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    strategy:
      matrix:
        project: [frontend, backend]
    steps:
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/turnier-app-${{ matrix.project }}:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/turnier-app-${{ matrix.project }}:latest'
          format: 'github'
          github-pat: ${{ secrets.GITHUB_TOKEN }}